"""0001_initial_all_24_tables

Revision ID: ac145788f17d
Revises: 
Create Date: 2026-08-06 21:45:18.044690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac145788f17d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('running_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code')
    )
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_location'), 'devices', ['location'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('version_name', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    op.create_index(op.f('ix_versions_release_date'), 'versions', ['release_date'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('auto_refresh', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_category'), 'dashboards', ['category'], unique=False)
    op.create_index(op.f('ix_dashboards_creator_id'), 'dashboards', ['creator_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_volume', sa.Integer(), nullable=False),
    sa.Column('sync_method', sa.String(length=20), nullable=False),
    sa.Column('sync_frequency', sa.String(length=50), nullable=True),
    sa.Column('sync_cron', sa.String(length=50), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_last_sync_at'), 'data_sources', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_data_sources_owner_id'), 'data_sources', ['owner_id'], unique=False)
    op.create_index(op.f('ix_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.create_index(op.f('ix_data_sources_type'), 'data_sources', ['type'], unique=False)
    op.create_table('inspection_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('scope_config', sa.JSON(), nullable=True),
    sa.Column('device_ids', sa.JSON(), nullable=True),
    sa.Column('inspection_metrics', sa.JSON(), nullable=True),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_plans_creator_id'), 'inspection_plans', ['creator_id'], unique=False)
    op.create_index(op.f('ix_inspection_plans_enabled'), 'inspection_plans', ['enabled'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_creator_id'), 'reports', ['creator_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_type'), 'reports', ['type'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_type'), 'dashboard_widgets', ['type'], unique=False)
    op.create_table('data_sync_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sync_method', sa.String(length=20), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sync_logs_source_id'), 'data_sync_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_data_sync_logs_started_at'), 'data_sync_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_data_sync_logs_status'), 'data_sync_logs', ['status'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('query_config', sa.JSON(), nullable=True),
    sa.Column('field_count', sa.Integer(), nullable=False),
    sa.Column('data_volume', sa.Integer(), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_datasets_source_id'), 'datasets', ['source_id'], unique=False)
    op.create_table('inspection_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('scope_config', sa.JSON(), nullable=True),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('overall_result', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['inspection_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_tasks_assignee_id'), 'inspection_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_inspection_tasks_plan_id'), 'inspection_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_inspection_tasks_scheduled_at'), 'inspection_tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_inspection_tasks_status'), 'inspection_tasks', ['status'], unique=False)
    op.create_table('dataset_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_alias', sa.String(length=100), nullable=True),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('is_dimension', sa.Boolean(), nullable=False),
    sa.Column('is_metric', sa.Boolean(), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_fields_dataset_id'), 'dataset_fields', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_fields_is_dimension'), 'dataset_fields', ['is_dimension'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('inspector_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('anomaly_desc', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_records_device_id'), 'inspection_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_inspected_at'), 'inspection_records', ['inspected_at'], unique=False)
    op.create_index(op.f('ix_inspection_records_result'), 'inspection_records', ['result'], unique=False)
    op.create_index(op.f('ix_inspection_records_task_id'), 'inspection_records', ['task_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_key_metric', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_category'), 'metrics', ['category'], unique=False)
    op.create_index(op.f('ix_metrics_dataset_id'), 'metrics', ['dataset_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('notify_methods', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_enabled'), 'alert_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_level'), 'alert_rules', ['level'], unique=False)
    op.create_index(op.f('ix_alert_rules_metric_id'), 'alert_rules', ['metric_id'], unique=False)
    op.create_table('metric_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('time_bucket', sa.DateTime(), nullable=False),
    sa.Column('granularity', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('dimension_key', sa.String(length=100), nullable=True),
    sa.Column('dimension_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_values_metric_id'), 'metric_values', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metric_values_time_bucket'), 'metric_values', ['time_bucket'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('metric_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('processor_id', sa.String(length=36), nullable=True),
    sa.Column('process_note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_assignee_id'), 'alerts', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assignee_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_metric_values_time_bucket'), table_name='metric_values')
    op.drop_index(op.f('ix_metric_values_metric_id'), table_name='metric_values')
    op.drop_table('metric_values')
    op.drop_index(op.f('ix_alert_rules_metric_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_level'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_enabled'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_metrics_dataset_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_category'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_inspection_records_task_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_result'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_inspected_at'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_device_id'), table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_dataset_fields_is_dimension'), table_name='dataset_fields')
    op.drop_index(op.f('ix_dataset_fields_dataset_id'), table_name='dataset_fields')
    op.drop_table('dataset_fields')
    op.drop_index(op.f('ix_inspection_tasks_status'), table_name='inspection_tasks')
    op.drop_index(op.f('ix_inspection_tasks_scheduled_at'), table_name='inspection_tasks')
    op.drop_index(op.f('ix_inspection_tasks_plan_id'), table_name='inspection_tasks')
    op.drop_index(op.f('ix_inspection_tasks_assignee_id'), table_name='inspection_tasks')
    op.drop_table('inspection_tasks')
    op.drop_index(op.f('ix_datasets_source_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_data_sync_logs_status'), table_name='data_sync_logs')
    op.drop_index(op.f('ix_data_sync_logs_started_at'), table_name='data_sync_logs')
    op.drop_index(op.f('ix_data_sync_logs_source_id'), table_name='data_sync_logs')
    op.drop_table('data_sync_logs')
    op.drop_index(op.f('ix_dashboard_widgets_type'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_reports_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_creator_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_inspection_plans_enabled'), table_name='inspection_plans')
    op.drop_index(op.f('ix_inspection_plans_creator_id'), table_name='inspection_plans')
    op.drop_table('inspection_plans')
    op.drop_index(op.f('ix_data_sources_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_status'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_owner_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_last_sync_at'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_dashboards_creator_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_category'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_versions_release_date'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_location'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
